resource_registry:
  OS::TripleO::AllNodes::SoftwareConfig: /usr/share/openstack-tripleo-heat-templates/puppet/all-nodes-config.yaml

  OS::TripleO::Compute::SoftwareConfig: /home/stack/openstack-templates/RDU-Perf/Ocata/SuperMicro/nic-configs/compute.yml
  OS::TripleO::Controller::SoftwareConfig: /home/stack/openstack-templates/RDU-Perf/Ocata/SuperMicro/nic-configs/controller.yml

parameter_defaults:
  NeutronExternalNetworkBridge: "''"
  InternalApiNetCidr: 172.16.0.0/24
  TenantNetCidr: 172.17.0.0/24
  StorageNetCidr: 172.18.0.0/24
  StorageMgmtNetCidr: 172.19.0.0/24
  ManagementNetCidr: 172.20.0.0/24
  ExternalNetCidr: 192.168.24.0/24
  InternalApiAllocationPools: [{'start': '172.16.0.10', 'end': '172.16.0.200'}]
  TenantAllocationPools: [{'start': '172.17.0.10', 'end': '172.17.0.200'}]
  StorageAllocationPools: [{'start': '172.18.0.10', 'end': '172.18.0.200'}]
  StorageMgmtAllocationPools: [{'start': '172.19.0.10', 'end': '172.19.0.200'}]
  ManagementAllocationPools: [{'start': '172.20.0.10', 'end': '172.20.0.200'}]
  ExternalAllocationPools: [{'start': '192.168.24.100', 'end': '192.168.24.250'}]
  # Set to the router gateway on the external network
  ExternalInterfaceDefaultRoute: 192.168.24.1
  PublicVirtualFixedIPs: [{'ip_address':'192.168.24.100'}]
  # Gateway router for the provisioning network (or Undercloud IP)
  ControlPlaneDefaultRoute: 192.168.24.1
  # The IP address of the EC2 metadata server. Generally the IP of the Undercloud
  EC2MetadataIp: 192.168.24.1
  # Define the DNS servers (maximum 2) for the overcloud nodes
  DnsServers: ["10.12.64.161"]
  InternalApiNetworkVlanID: 301
  StorageNetworkVlanID: 302
  StorageMgmtNetworkVlanID: 303
  TenantNetworkVlanID: 304
  ManagementNetworkVlanID: 305
  #ExternalNetworkVlanID: 10
  # Set to "br-ex" if using floating IPs on native VLAN on bridge br-ex
  BondInterfaceOvsOptions: "lacp=active other-config:lacp-fallback-ab=true"

